version: '3.7'

volumes:
    prometheus_data: {}

networks:
  pilz-network:

services:

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./src/nginx/www:/usr/share/nginx/html
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pilz-network

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: 'nginx-exporter'
    environment:
      - SCRAPE_URI=http://nginx:80/nginx_status
    ports:
      - 9113:9113
    depends_on:
      - nginx
    networks:
      - pilz-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./src/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - nginx:nginx
      - nginx-exporter:nginx-exporter
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    networks:
      - pilz-network
    restart: always

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./src/alertmanager/:/etc/alertmanager/
    networks:
      - pilz-network
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - pilz-network
    restart: always
    deploy:
      mode: global